### ISSUE TITLE
Versioning error

### ISSUE THREAD

**Issue by MatchTerm** [snackerpirater/actualcbcnukes#3]
Hello!

Just to warn you, big cannons has changed how versioning works, so the addon is getting confused, since now with these changes, the current big cannon version is 5.5.0

**Comment by snackerpirater** [comment]
This is intentional, as CBC Nuclear is not updated for version 5.5.0 of CBC; that version is mildly broken so I'm waiting for 5.5.1 to properly update Nuclear.

**Comment by MatchTerm** [comment]
Ah ok, thanks!
