### ISSUE TITLE
Version mismatch? 1.0.0 from Modrinth for Forge 1.20.1

### ISSUE THREAD

**Issue by zaafonin** [snackerpirater/actualcbcnukes#4]
![image](https://github.com/user-attachments/assets/5dc3eed4-7270-4c87-bee0-d3c52618ec80)

**Comment by snackerpirater** [comment]
Intended; I have not updated CBC Nukes to the latest version of CBC yet.

**Comment by zaafonin** [comment]
Is that in plans for 1.20.1? Doesn't look like a huge mod to update so fingers crossed
